### ISSUE TITLE
Losing drag and drop ability after some time

### ISSUE THREAD

**Issue by skrivskithar** [gmail-manager-community/gmail-manager-community#40]
I'm on FF 45.0.1 and this has been happening since the fix that fixed the bug disabling drag and drop at all. After some time, it stops working and I need to restart FF

**Comment by skrivskithar** [comment]
also happens on FF 47.0.1

**Comment by skrivskithar** [comment]
anyone else having this issue?

edit: it's definitely related to snippets. I disabled them and I'm still being able to drag and drop after hours

**Comment by ath0mas** [comment]
Using Gmail Manager-community 0.7.1 ?

**Comment by skrivskithar** [comment]
Yes, since it was released.

**Comment by mincem** [comment]
This happened to me today, for the first time since #29 was fixed.
After a few quick tests, it seems to happen to me every time the snippets window opens, provided that:
- there are 2 or more unread messages, and
- the first message to display has an empty body (doesn't matter if subject is empty or not)

Symptoms are as follows:
- snippet window can be seen going down to the bottom of the screen (on top of every other object)
- drag & drop stops working
- Firefox process keeps running when you close all windows

(Also, when I tested a single unread message with no body, sometimes snippets wouldn't show at all, but that didn't happen consistently, so I'm not sure.)

**Comment by ath0mas** [comment]
@skrivskithar @mincem 0.7.1.1 released today, with changes on how snippet window slides up and down
can you check if things work better? about drag and drop issue, and Firefox process not exiting

**Comment by skrivskithar** [comment]
working fine so far! Have been testing it for about 4 hours. Thanks for the update!

**Comment by pvkid** [comment]
Working just fine for me also :)

**Comment by mincem** [comment]
It works for me too.

It still feels weird to me that the snippet window is visible in front of the taskbar. I think it used to emerge from behind it.
