### ISSUE TITLE
Not showing new e-mails

### ISSUE THREAD

**Issue by gmng** [gmail-manager-community/gmail-manager-community#49]
Since FF51 it does not showing new mails, the icon stays red, but there are new mails in the account.
I also frequently get greyed out icon showing it could not check for new mails.

**Comment by AMDZen** [comment]
I don't think your issue is related to the new FF, and probably have something similar to what I have going on.

Mods / devs

My issue was closed but was never resolved.  I updated it with new information - please see my issue here 

https://github.com/gmail-manager-community/gmail-manager-community/issues/26

**Comment by gmng** [comment]
I disabled and re-enabled the add-on and it works. Sorry! I don't know what has caused this.
