### ISSUE TITLE
(null) displayed on tooltip randomly but only since switch from Chat to Hangouts?

### ISSUE THREAD

**Issue by pssonline** [gmail-manager-community/gmail-manager-community#51]
Hi all,

Apologies for starting a new issue when it may very well be related to existing ones but as per the title, I'm not entirely sure.

-I've been using GMC with no problems whatsoever up until last week, not seeing any of the existing, outstanding issues

- Each of my accounts displayed a prompt to switch from Chat to Hangouts. I don't use either functionality and never have, but effecting the switch made the prompt disappear on all my accounts

- Since then I get (null) displayed on the tooltip and no email notifications randomly across all of my four GMail accounts.

- I've logged out of all accounts and deleted all Google cookies to no real avail. I still get the issue as per the attached screenshot but which account is effected appears random.

I'm a tad confused re the timing and the switch from Chat to Hangouts having a potential impact. Ideas very much appreciated!
![gmail_manager_2](https://cloud.githubusercontent.com/assets/28197193/25557062/7e1cef04-2d4c-11e7-9b03-b905cf577ad1.jpg)

**Comment by mincem** [comment]
Hi, I've been getting a lot of (null)s too, for a few days now. Most times, the problem goes away if I close Firefox and open it again. (Using the reset option doesn't have the same result, though.)

I don't think it's related to Hangouts, that was probably a coincidence.

**Comment by mDisna** [comment]
Are you getting the new Gmail login screen for that account? I am getting that new login screen on the account that shows null, but unsure if it's related since another account is showing the number of emails correctly.

**Comment by pssonline** [comment]
I have to do some more testing to be 100% sure but so far there may be a connection; 2 out of 4 accounts have the new login and GMC shows null for these but not the others.

**Comment by Endor8** [comment]
I can confirm this. Same here. I have now on all 5 accounts the new Gmail login screen.
Only on the start of Firefox it works or on restart, but then only 0 is displayed.

**Comment by stavrosthewonderchicken** [comment]
Confirming the issue here, too, since rollout of new login pages started.

**Comment by pssonline** [comment]
It's far less elegant than GMC, but I've had to switch to [https://addons.mozilla.org/en-GB/firefox/addon/gmail-notifier-restartless/](url) in the meantime as this current issue has left it unworkable for me.

**Comment by jrddyson** [comment]
All my accounts are also now displaying 0 unread and "(null) important unread message(s)".  GMC is unuseable in this state.

**Comment by damienfournier** [comment]
Ok, what I have found so far:

> the url for login has changed from https://accounts.google.com/ServiceLoginAuth?service=mail to https://accounts.google.com/signin/v2/identifier?service=mail&flowName=GlifWebSignIn&flowEntry=ServiceLogin

> in gmServiceGmail.js, lines 139 & following: "Email" should be "identifier" and "Passwd" should be "password" (new input names)

It still doesn't work...
The problem seems to be that there are 2 login pages to go through (email then password) whereas the plugin tries to login all in one place...

Edit:
- I don't think we can login in one step... there should be some csrf protection to prevent that
- I don't know how to log in with 2 login pages in the plugin (I can do that in Php, but not in this js async callback garbage hell thing)
- So, I think the possibilities are:
-- someone can modify the plugin to have a double login process
-- someone can modify the plugin to use apis instead of faking an user login
-- we're screwed and the plugin is nearly useless
-- there are other possibilities that I haven't found
- @ath0mas any progress on this ?

**Comment by m-soltys** [comment]
I noticed today that the GMC isn't working for me. I will try to fix this.

 **@ath0mas** are you here to accept the PR when I will find the solution?

Edit:

Fixed, the GMC is working again. Tomorrow I will do some tidy up and create a PR.

**Comment by stavrosthewonderchicken** [comment]
Excellent news @m-soltys -- thanks for that. Can't live without GMC after all these years.

**Comment by m-soltys** [comment]
The PR created. Waiting for **@ath0mas** to review.

**Comment by ath0mas** [comment]
Any PR is really welcome for sure

**Comment by ath0mas** [comment]
I should have time to start test/review on tuesday
Please community feel free to help with test and review too :)

**Comment by m-soltys** [comment]
If anybody wants to help with tests or get the working add-on faster I've created signed xpi version for that purpose:

[https://drive.google.com/open?id=0B0ll5y9t_HpYaFpVM2xBMW8yUjQ](https://drive.google.com/open?id=0B0ll5y9t_HpYaFpVM2xBMW8yUjQ)

To use my working version instead of the broken GMC version, you need to go to the 'Add-ons' page by menu Tools -> Add-ons or by shortcut Ctrl + Shift + A, remove the original GMC add-on and install downloaded xpi by the gearbox icon in the top right -> 'Install Add-on from file'. All configured accounts should be there after restarting the Firefox.

I will try to fix #45 issue with 1-click-auto-connect.

**Comment by mDisna** [comment]
Thanks for the xpi - right off the bat, it appears to have fixed the issue. Will add more accounts and do more testing.

**Comment by m-soltys** [comment]
@mDisna any feedback from tests will be appreciated

**Comment by m-soltys** [comment]
New version with fixed 1 click login.

[https://drive.google.com/file/d/0B0ll5y9t_HpYSFM0RmprM0JtSWs/view?usp=sharing](https://drive.google.com/file/d/0B0ll5y9t_HpYSFM0RmprM0JtSWs/view?usp=sharing)

Please test and report any problems and issues. I have some doubts that not every Gmail account has the two step verification enabled and there are some accounts that still use an old one step login way.

**Comment by mDisna** [comment]
Working flawlessly for me so far - thanks for working on this!

**Comment by tydeus** [comment]
Everything's working perfectly for me as well,  appreciated m-soltys!

**Comment by jrddyson** [comment]
@m-soltys Also working perfectly for me, thank you Marcin.

**Comment by chiby88** [comment]
Working perfectly on all my 6 accounts. Thanks!

**Comment by Endor8** [comment]
@m-soltys
I can confirm, now it works perfectly. Thank you. But there is a new issue now.
With the not working Version, when you click on the snippets of new E-Mails it 
opens a New Tab in the background and performs login to Gmail, since issue #45 ,
of curse opens only the login page.
Now nothing happens when you click.  Please take a look on it.
Cheers
Endor

**Comment by m-soltys** [comment]
@Endor8 thanks for info. Will look at this.

**Comment by m-soltys** [comment]
@Endor8 fixed. When you click on the e-mail body on the snippet it opens that e-mail in the background.

[https://drive.google.com/open?id=0B0ll5y9t_HpYV2dwUWVGQm5zM1E](https://drive.google.com/open?id=0B0ll5y9t_HpYV2dwUWVGQm5zM1E)

**Comment by Endor8** [comment]
Thank you. I try it out. I will report the result.

**Comment by Endor8** [comment]
Yea. Fantastic. Now works perfect.
Thank you very much.
Cheers
Endor

**Comment by pssonline** [comment]
Many thanks @m-soltys your work is much appreciated!

**Comment by sunup** [comment]
Working beautifully. Thanks @m-soltys for your efforts.

**Comment by testuser7** [comment]
@m-soltys thank you for your effort.

Can you take a look at issue #22 ?
On my Firefox icon is disappearing after open new pop-up window.

**Comment by m-soltys** [comment]
@testuser7 I can look at this but you have to provide reliable steps to reproduce this issue and info about your browser and the GMC version.

**Comment by ath0mas** [comment]
@testuser7 it's not the right place, please create new issue with details

**Comment by rucksman** [comment]
Any idea when the PR will be integrated and the new version will be available from addons.mozilla.org?

**Comment by damienfournier** [comment]
@ath0mas do you need help with the pull request ?
We use this addon at work so the sooner it's online the better :)

A big thanks to @m-soltys for the fix !

**Comment by ath0mas** [comment]
@damienfournier read and comment as a code review would help yes
Did not had time this week-end, sorry... I'll make my best to take time this week, monday or tueday max I hope

**Comment by rucksman** [comment]
Any progress on this? What can be done to solve this? @damienfournier offered his help already, I would also be available for help. It's not that many lines of code to check from what I see in the PR. The incredible @m-soltys did this amazing PR 2 weeks ago already so it would be more than fair to honor his effort in getting his version out...

**Comment by ath0mas** [comment]
@rucksman see PR #53 to follow/be part of review
at the moment, _login_ issue seems to be fixed but submitted changes for 1-click auto-connect work only for some accounts, not all
\+ I just reviewed code, and as I said, I would like to submit a new release quickly then to have 2-step login even if auto-connect is not fully working (would be better than not working at all like it currently is 😉)

**Comment by bacon-cheeseburger** [comment]
@ath0mas The plugin has been broken for a long time. I think it's better to get it working 100% before doing a new release than just rushing a half-working one out the door. We've waited this long, we can wait a little longer if it means a fully working update. Just my $.02.

**Comment by m-soltys** [comment]
I can't get it working 100% because I'm not familiar with Firefox extensions and don't have much time to guessing why it's working for most of the users and doesn't work for some of you guys. 

If someone can provide me a non working test account or debug why it's not working for him I will be able to provide a permanent fix. My fix 
is working just fine for people around me and for myself.

**Comment by bacon-cheeseburger** [comment]
To anyone who is having problems with m-soltys's fixes, did you remember to either uninstall or disable the previous gmc _before_ installing and restarting m-soltys? I initially had issues but it was because I forgot to disable the old one. After disabling it , everything is fine. I also had to replace the icon in the addon bar so it linked to m-soltys.

**Comment by internero** [comment]
I did exactly what you said: removed official add-on and installed .xpi
from m-soltys link.

Everithing is working perfect. BUT, 1 account (and just one!) cannot
connect. When I click on it, the new tab shows me the standard login page
for gmail, with password field.

Since its a gapps account, I've tried to create another account in the same
domain, but the pluginworked as expected with this new accoun.

So, I can't help giving access to a problematic account.

Can I grab logs to send ? Can anyone gimme instructions on how to grab
these logs ?

Thanks.


internero@gmail.com

**Comment by ath0mas** [comment]
With my test account, in Firefox Dev Edition, I finally got 1-click to work, no more cookie info or login pages

Inside "Privacy" > "History" settings from Firefox **Options** page:
* _Never remember history_ = ❌ 
* _Use custom settings for history_
  * "Always use private browsing mode" **checked** + "Accept cookies from sites" **checked** = ❌  
  * "Always use private browsing mode" **unchecked** + "Accept cookies from sites" **checked** = ✔️ 

("Accept cookies from sites" with whatever options for "Accept cookies from sites" and "Keep until")

**Comment by ath0mas** [comment]
PR #53 merged
release and _deploy_ to come soon

**Comment by ath0mas** [comment]
0.7.2 released, please update
Confirm issue can be closed?

**Comment by damienfournier** [comment]
@ath0mas works for me ! 
big thanks to all

**Comment by Endor8** [comment]
@ath0mas works for me too!
big thanks to all

**Comment by bacon-cheeseburger** [comment]
Thanks guys!
